# Generated by Django 6.0.6 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_employeeprofile_dob_employeeprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_type',
            field=models.CharField(choices=[('FRESHER', 'Fresher'), ('EXPERIENCED', 'Experienced')], default='FRESHER', max_length=20),
        ),
    ]
